package NuCalendar.TableGUI;


import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 * @author Alec Freeman
 */
public class EventDisplay extends javax.swing.JFrame {

    /**
     * Creates new form EventDisplay
     */
    public EventDisplay() {
        super();
//        startupSlide();
//        startupPull();
        initComponents();
    }

    
    void dateReadoutForMonths(ArrayList<String> labelsMonths) {
        for (String s : labelsMonths) {
            eventMonth.setText(s);
        }
    }
    void dateReadoutForYears(ArrayList<String> labelsYears) {
        for (String s : labelsYears) {
            eventYear.setText(s);
        }
    }
    void dateReadoutForDays(ArrayList<Integer> labelsDays) {
        for (Integer i : labelsDays) {
            eventDay.setText(i.toString());
        }
    }
    /**
     * Get events for day.
     */
    public void rePopulate(ArrayList<Event> e) {
        for (Event j : e) {
            eventWindow.append("Event Title: " + j.getName() + "\r\n");
            eventWindow.append("Event Date: " + j.getStartDate().toString() + "\r\n");
            eventWindow.append("Event Description: " + j.getLocation() + "\r\n");
            /**
             * Dash separator.
             */
            eventWindow.append("----------------------\r\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventPanel = new javax.swing.JPanel();
        eventScroll = new javax.swing.JScrollPane();
        eventWindow = new javax.swing.JTextArea();
        eventMonth = new javax.swing.JLabel();
        eventDay = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eventYear = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        eventPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Date & Event Display"));

        eventWindow.setEditable(false);
        eventWindow.setColumns(20);
        eventWindow.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        eventWindow.setRows(5);
        eventWindow.setWrapStyleWord(true);
        eventScroll.setViewportView(eventWindow);

        eventMonth.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eventMonth.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        eventMonth.setText("jLabel1");

        eventDay.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eventDay.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        jLabel1.setText(",");

        eventYear.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        eventYear.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        eventYear.setText("jLabel2");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout eventPanelLayout = new javax.swing.GroupLayout(eventPanel);
        eventPanel.setLayout(eventPanelLayout);
        eventPanelLayout.setHorizontalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eventScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
                    .addGroup(eventPanelLayout.createSequentialGroup()
                        .addComponent(eventMonth)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eventYear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        eventPanelLayout.setVerticalGroup(
            eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eventPanelLayout.createSequentialGroup()
                .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(eventPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eventDay)
                                .addComponent(jLabel1)
                                .addComponent(eventYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(eventMonth)))
                    .addComponent(jSeparator1))
                .addGap(4, 4, 4)
                .addComponent(eventScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eventPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eventDay;
    private javax.swing.JLabel eventMonth;
    private javax.swing.JPanel eventPanel;
    private javax.swing.JScrollPane eventScroll;
    private javax.swing.JTextArea eventWindow;
    private javax.swing.JLabel eventYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
